sponsors:
  - name: Codurance
    url: https://codurance.com/
    logo: codurance.png 

  - name: Armakuni
    url: https://armakuni.com/
    logo: armakuni.jpg

  - name: Zopa
    url: https://www.zopa.com/
    logo: Zopa_Logo_PNG.png

  - name: Runpath
    url: https://www.runpath.com/
    logo: runpath.png

event_details:
  year: 2024
  date: Sept 19th-22nd
  location: Milton Hill House, Abingdon, OX13 6AF

partner_events:
  - title: CodeFreeze
    website: https://codefreeze.fi/
    date: January 7th - 14th 2023
    location: Kiilopää, Finland

  - title: SoCraTes Switzerland
    website: http://www.socrates-ch.org/
    date: February 2nd - 5th 2023
    location: Ilanz, Switzerland

  - title: SoCraTes Canada
    website: https://socrates-ca.github.io
    date: March 13th - 15th  2020
    location: Amherst, Canada

  - title: SoCraTes Maroc
    website: https://socrates-ma.github.io
    date: March 10th - 12th 2023
    location: Bouznika, Marocco

  - title: SoCraTes Canaries
    website: https://www.socracan.com/
    date: May 11th - 14th 2023
    location: Santa Cruz de Tenerife, Spain

  - title: I T.A.K.E. Unconference
    website: https://mozaicworks.com/product/i-t-a-k-e-unconference
    date: May 25th - 26th 2022
    location: Bucharest, Romania

  - title: SoCraTes Day Chile
    website: https://www.socrates-conference.cl/
    date: TBC
    location: Santiago de Chile, Chile

  - title: AgileCrete
    website: https://agilecrete.org/
    date: June 9th - 12th 2022
    location: Kolymbari, Crete

  - title: JS CraftCamp
    website: http://jscraftcamp.org/
    date: June 17th - 18th 2022
    location: Munich, Germany

  - title: SoCraTes BE
    website: https://socratesbe.org/
    date: July 7th - 10th 2022
    location: La Roche-en-Ardenne, Belgium

  - title: SoCraTes Germany
    website: https://www.socrates-conference.de/
    date: August 25th - 28th  2022
    location: Soltau, Germany

  - title: SoCraTes Day Berlin
    website: http://www.socratesday.berlin/
    date: TBC
    location: Berlin, Germany

  - title: SoCraTes Day Zurich
    website: http://socrates-day.ch/
    date: Friday 16th September 2022
    location: Zürich, Switzerland

  - title: SoCraTes Italy
    website: http://www.socrates-conference.it/
    date:  September 22nd - 24th 2022
    location: Rimini, Italy

  - title: SoCraTes France
    website: https://socrates-fr.github.io/
    date: October 17-20th 2022
    location: Uchaux, France

markdown: kramdown
