sponsors:
  - name: Aspect Capital 
    url: https://www.aspectcapital.com
    logo: aspect_capital_logo.png 
  - name: Unruly
    url: https://unruly.co
    logo: unruly_logo.png 
  - name: Zopa
    url: https://www.zopa.com/
    logo: Zopa_Logo_PNG.png 
  - name: Medidata
    url: https://www.mdsol.com/en
    logo: Medidata_Logo_PNG.png  

markdown: kramdown
